pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                script {
                    docker.image('node:16-alpine').inside('-w /c/ProgramData/Jenkins/.jenkins/workspace/pipe') {
                        sh 'node --version'
                    }
                }
            }
        }
    }
}
